name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Kubernetes YAML
      uses: instrumenta/kubeval-action@master
      with:
        files: "kubernetes/*.yaml"
